[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "SpatialGlue"
authors = [{name = "Zhikang Wang", email = "zhikang.wang@monash.edu"}]
dynamic = ["version", "description"]
